return {
	{ label = "GraalVM Native Support", insertText = "native," },
	{ label = "GraphQL DGS Code Generation", insertText = "dgs-codegen," },
	{ label = "Spring Boot DevTools", insertText = "devtools," },
	{ label = "Lombok", insertText = "lombok," },
	{ label = "Spring Configuration Processor", insertText = "configuration-processor," },
	{ label = "Docker Compose Support", insertText = "docker-compose," },
	{ label = "Spring Modulith", insertText = "modulith," },
	{ label = "Spring Web", insertText = "web," },
	{ label = "Spring Reactive Web", insertText = "webflux," },
	{ label = "Spring for GraphQL", insertText = "graphql," },
	{ label = "Rest Repositories", insertText = "data-rest," },
	{ label = "Spring Session", insertText = "session," },
	{ label = "Rest Repositories HAL Explorer", insertText = "data-rest-explorer," },
	{ label = "Spring HATEOAS", insertText = "hateoas," },
	{ label = "Spring Web Services", insertText = "web-services," },
	{ label = "Jersey", insertText = "jersey," },
	{ label = "Vaadin", insertText = "vaadin," },
	{ label = "Hilla", insertText = "hilla," },
	{ label = "Thymeleaf", insertText = "thymeleaf," },
	{ label = "Apache Freemarker", insertText = "freemarker," },
	{ label = "Mustache", insertText = "mustache," },
	{ label = "Groovy Templates", insertText = "groovy-templates," },
	{ label = "Spring Security", insertText = "security," },
	{ label = "OAuth2 Client", insertText = "oauth2-client," },
	{ label = "OAuth2 Authorization Server", insertText = "oauth2-authorization-server," },
	{ label = "OAuth2 Resource Server", insertText = "oauth2-resource-server," },
	{ label = "Spring LDAP", insertText = "data-ldap," },
	{ label = "Okta", insertText = "okta," },
	{ label = "JDBC API", insertText = "jdbc," },
	{ label = "Spring Data JPA", insertText = "data-jpa," },
	{ label = "Spring Data JDBC", insertText = "data-jdbc," },
	{ label = "Spring Data R2DBC", insertText = "data-r2dbc," },
	{ label = "MyBatis Framework", insertText = "mybatis," },
	{ label = "Liquibase Migration", insertText = "liquibase," },
	{ label = "Flyway Migration", insertText = "flyway," },
	{ label = "JOOQ Access Layer", insertText = "jooq," },
	{ label = "IBM DB2 Driver", insertText = "db2," },
	{ label = "Apache Derby Database", insertText = "derby," },
	{ label = "H2 Database", insertText = "h2," },
	{ label = "HyperSQL Database", insertText = "hsql," },
	{ label = "MariaDB Driver", insertText = "mariadb," },
	{ label = "MS SQL Server Driver", insertText = "sqlserver," },
	{ label = "MySQL Driver", insertText = "mysql," },
	{ label = "Oracle Driver", insertText = "oracle," },
	{ label = "PostgreSQL Driver", insertText = "postgresql," },
	{ label = "Spring Data Redis (Access+Driver)", insertText = "data-redis," },
	{ label = "Spring Data Reactive Redis", insertText = "data-redis-reactive," },
	{ label = "Spring Data MongoDB", insertText = "data-mongodb," },
	{ label = "Spring Data Reactive MongoDB", insertText = "data-mongodb-reactive," },
	{ label = "Spring Data Elasticsearch (Access+Driver)", insertText = "data-elasticsearch," },
	{ label = "Spring Data for Apache Cassandra", insertText = "data-cassandra," },
	{ label = "Spring Data Reactive for Apache Cassandra", insertText = "data-cassandra-reactive," },
	{ label = "Spring Data Couchbase", insertText = "data-couchbase," },
	{ label = "Spring Data Reactive Couchbase", insertText = "data-couchbase-reactive," },
	{ label = "Spring Data Neo4j", insertText = "data-neo4j," },
	{ label = "Spring Integration", insertText = "integration," },
	{ label = "Spring for RabbitMQ", insertText = "amqp," },
	{ label = "Spring for Apache Kafka", insertText = "kafka," },
	{ label = "Spring for Apache Kafka Streams", insertText = "kafka-streams," },
	{ label = "Spring for Apache ActiveMQ 5", insertText = "activemq," },
	{ label = "Spring for Apache ActiveMQ Artemis", insertText = "artemis," },
	{ label = "Spring for Apache Pulsar", insertText = "pulsar," },
	{ label = "Spring for Apache Pulsar (Reactive)", insertText = "pulsar-reactive," },
	{ label = "WebSocket", insertText = "websocket," },
	{ label = "RSocket", insertText = "rsocket," },
	{ label = "Apache Camel", insertText = "camel," },
	{ label = "Solace PubSub+", insertText = "solace," },
	{ label = "Spring Batch", insertText = "batch," },
	{ label = "Validation", insertText = "validation," },
	{ label = "Java Mail Sender", insertText = "mail," },
	{ label = "Quartz Scheduler", insertText = "quartz," },
	{ label = "Spring Cache Abstraction", insertText = "cache," },
	{ label = "Picocli", insertText = "picocli," },
	{ label = "Spring Shell", insertText = "spring-shell," },
	{ label = "Timefold Solver", insertText = "timefold-solver," },
	{ label = "Spring Boot Actuator", insertText = "actuator," },
	{ label = "codecentric's Spring Boot Admin (Client)", insertText = "codecentric-spring-boot-admin-client," },
	{ label = "codecentric's Spring Boot Admin (Server)", insertText = "codecentric-spring-boot-admin-server," },
	{ label = "Sentry", insertText = "sentry," },
	{ label = "Datadog", insertText = "datadog," },
	{ label = "Dynatrace", insertText = "dynatrace," },
	{ label = "Influx", insertText = "influx," },
	{ label = "Graphite", insertText = "graphite," },
	{ label = "New Relic", insertText = "new-relic," },
	{ label = "Prometheus", insertText = "prometheus," },
	{ label = "Distributed Tracing", insertText = "distributed-tracing," },
	{ label = "Wavefront", insertText = "wavefront," },
	{ label = "Zipkin", insertText = "zipkin," },
	{ label = "Spring REST Docs", insertText = "restdocs," },
	{ label = "Testcontainers", insertText = "testcontainers," },
	{ label = "Contract Verifier", insertText = "cloud-contract-verifier," },
	{ label = "Contract Stub Runner", insertText = "cloud-contract-stub-runner," },
	{ label = "Embedded LDAP Server", insertText = "unboundid-ldap," },
	{ label = "Cloud Bootstrap", insertText = "cloud-starter," },
	{ label = "Function", insertText = "cloud-function," },
	{ label = "Task", insertText = "cloud-task," },
	{ label = "Config Client", insertText = "cloud-config-client," },
	{ label = "Config Server", insertText = "cloud-config-server," },
	{ label = "Vault Configuration", insertText = "cloud-starter-vault-config," },
	{ label = "Apache Zookeeper Configuration", insertText = "cloud-starter-zookeeper-config," },
	{ label = "Consul Configuration", insertText = "cloud-starter-consul-config," },
	{ label = "Eureka Discovery Client", insertText = "cloud-eureka," },
	{ label = "Eureka Server", insertText = "cloud-eureka-server," },
	{ label = "Apache Zookeeper Discovery", insertText = "cloud-starter-zookeeper-discovery," },
	{ label = "Consul Discovery", insertText = "cloud-starter-consul-discovery," },
	{ label = "Gateway", insertText = "cloud-gateway," },
	{ label = "Reactive Gateway", insertText = "cloud-gateway-reactive," },
	{ label = "OpenFeign", insertText = "cloud-feign," },
	{ label = "Cloud LoadBalancer", insertText = "cloud-loadbalancer," },
	{ label = "Resilience4J", insertText = "cloud-resilience4j," },
	{ label = "Cloud Bus", insertText = "cloud-bus," },
	{ label = "Cloud Stream", insertText = "cloud-stream," },
	{ label = "Config Client (TAS)", insertText = "scs-config-client," },
	{ label = "Service Registry (TAS)", insertText = "scs-service-registry," },
	{ label = "Azure Support", insertText = "azure-support," },
	{ label = "Azure Active Directory", insertText = "azure-active-directory," },
	{ label = "Azure Cosmos DB", insertText = "azure-cosmos-db," },
	{ label = "Azure Key Vault", insertText = "azure-keyvault," },
	{ label = "Azure Storage", insertText = "azure-storage," },
	{ label = "Google Cloud Support", insertText = "cloud-gcp," },
	{ label = "Google Cloud Messaging", insertText = "cloud-gcp-pubsub," },
	{ label = "Google Cloud Storage", insertText = "cloud-gcp-storage," },
}
